### ISSUE TITLE
Invalid Syntax error in Supplements

### ISSUE THREAD

**Issue by davegildea** [Yelp/fuzz-lightyear#48]
Hi Guys

I am getting the following error when I am running basic commands

`[ec2-user yelp]fuzz-lightyear -h
Traceback (most recent call last):
  File "/usr/bin/fuzz-lightyear", line 11, in <module>
    load_entry_point('fuzz-lightyear==0.0.6', 'console_scripts', 'fuzz-lightyear')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/fuzz_lightyear/__init__.py", line 1, in <module>
    from .supplements import exclude                        # noqa: F401
  File "/usr/lib/python2.7/site-packages/fuzz_lightyear/supplements/exclude.py", line 30
    def non_vulnerable_operations(func: Callable) -> Callable:
                                      ^
SyntaxError: invalid syntax`

Any help would be really appreciated? Not sure if I am missing something in the installation

Thanks

Dave

**Comment by davegildea** [comment]
Sorry, python 2 vs python 3 issue. Working successfully with Python 3.6, 

Thanks
Dave
